### PR TITLE
Change the order in which build-env args are parsed so it can be used in TEST_COMMAND of ExternalProject_Add

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by greenc-FNAL** [comment]
Is there a reason you're using `--prompt`? It would seem to be of limited use in a non-interactive context. Also, `--cd` should be redundant.

**Comment by gartung** [comment]
I forgot to remove it. Power is out at home, otherwise I would do it.

**Comment by greenc-FNAL** [comment]
OK, I think this points up a deficiency in `spack dev init`, which is failing to clean up a reference to the temporary staging area in the environment, leading to an incorrect setting for `PATH`. I'm out of time for today, but I'll take a look in the morning.

**Comment by gartung** [comment]
Defer to Chris' solution which incorporates the changes to build_env.pu

**Pull request closed without merging**
